spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  web:
    resources:
      static-locations: file:./upload/images/
      add-mappings: false

upload:
  path: upload/images

telegram:
  token: 7625407687:AAFy-u9xQNpzavjupGTiTFS-Wd40rRHYBGs
  username: congratulatorBot
  chatId: 2123207382